// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAuthenticationJWTGenerated.Data;

#nullable disable

namespace UserAuthenticationJWTGenerated.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20221226145518_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserAuthenticationJWTGenerated.Dtos.RegisterDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AadharCard")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AltMobNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnySocialGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GochriSeva")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameOfOrganization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestAirport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestBusStation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestRailwayStation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RouteCoordinator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TownOrDistrict")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViharSeva")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RegisterDtos");
                });

            modelBuilder.Entity("UserAuthenticationJWTGenerated.Models.VulunteerRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AadharCard")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AltMobNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnySocialGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GochriSeva")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameOfOrganization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestAirport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestBusStation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestRailwayStation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RouteCoordinator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TownOrDistrict")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViharSeva")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
